export const LOAD_USER_LIST = "LOAD_USER_LIST";
export const LOAD_USER_DETAIL = "LOAD_USER_DETAIL";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const SET_ADDED_USER = "SET_ADDED_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SET_UPDATED_USER = "SET_UPDATED_USER";
export const DELETE_USER = "DELETE_USER";
export const SET_DELETED_USER = "SET_DELETED_USER";
export const RESET_FORM_EDIT_ADD = "RESET_FORM_EDIT_ADD";

